### PR TITLE
Improve german locale

### PR DESCRIPTION
**Pull request by dalori**
I added some improvements to the DE locale. I was not able to do modal_setup_title_tilelayer since I miss the exact context of this translations.

### CODE REVIEW

**Comment by nlehuby** [comment]
The modal_setup_title_tilelayer is the title of the tab to change the tilelayer in the setup modal (the blue highlighted zone in the capture) : 
obm

**Comment by dalori** [comment]
Does it matter for a user if the background is a tile layer or not? In the end the map background changes, so I would go for a German equivalent of "Map background".

**Comment by nlehuby** [comment]
Totally ok, the French translation ("Fond de carte") also means "Map background".

**Comment by dalori** [comment]
Done, added the last missing one I found

**Comment by nlehuby** [comment]
Can you please add yourself to the contributors list ?

**Comment by dalori** [comment]
Of course, will do this now.

**Comment by OpenBeerMap** [comment]
:+1:

**Pull request merged**
